# Generated by Django 6.0.4 on 2026-05-08 07:30

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('children', '0002_child'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='allergies',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list),
        ),
    ]
