# Generated by Django 6.0.4 on 2026-05-08 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('children', '0003_child_allergies'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChildContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('relation', models.CharField(choices=[('FATHER', 'Père'), ('MOTHER', 'Mère'), ('GRANDFATHER', 'Grand-père'), ('GRANDMOTHER', 'Grand-mère'), ('UNCLE', 'Oncle'), ('AUNT', 'Tante'), ('SIBLING', 'Frère/Sœur'), ('NANNY', 'Nounou'), ('NEIGHBOR', 'Voisin'), ('OTHER', 'Autre')], max_length=20)),
                ('photo_url', models.URLField(blank=True)),
                ('is_authorized_pickup', models.BooleanField(default=False)),
                ('is_emergency_contact', models.BooleanField(default=False)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='children.child')),
            ],
        ),
    ]
