# Generated by Django 6.0.4 on 2026-05-08 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_managers'),
        ('children', '0004_childcontact'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='school',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='accounts.school'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='childcontact',
            name='school',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='child_contacts', to='accounts.school'),
            preserve_default=False,
        ),
    ]
