# Generated by Django 6.0.4 on 2026-05-10 01:24

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_user_group'),
        ('children', '0006_childparent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('CHECKIN', 'Arrivée'), ('CHECKOUT', 'Départ'), ('MEAL', 'Repas'), ('NAP', 'Sieste'), ('NOTE', 'Note'), ('PHOTO', 'Photo')], max_length=20)),
                ('note', models.TextField(blank=True)),
                ('photo_url', models.URLField(blank=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='children.child')),
                ('logged_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logged_activities', to=settings.AUTH_USER_MODEL)),
                ('picked_up_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pickups', to='children.childcontact')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='accounts.school')),
            ],
        ),
    ]
